# Generated by Django 6.1.1 on 2026-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('isBestSeller', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=100)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
    ]
